name: Deploying Express Notes app using CI/ED
on:
  push:
    branches:
      - main
jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from github to ubuntu
        uses: actions/checkout@v4
      - name: Configure AWS
        uses: aws-action/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to ECR
        uses: aws-action/amazon-ecr-login@v2
      - name: Creating build of our project
        run: |
          docker build -t express_notes_api:latest .
      - name: Adding tag
        run: |
          docker tag express_notes_api:latest ${{ secrets.ECR_REPO }}/express_notes_api:latest
      - name: Pushing registery on docker hub
        run: |
          docker push ${{ secrets.ECR_REPO }}/express_notes_api:latest
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }}
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}
            cd /home/ubuntu
            docker compose pull
            docker compose up -d --force-recreate
